export type CitySeed = {
  id: string;
  name: string;
  iataCity: string;
  timezone: string;
  tier: 1 | 2 | 3;
  aliases: string[];
};

export const CITIES: CitySeed[] = [
  {
    id: "MOW",
    name: "Москва",
    iataCity: "MOW",
    timezone: "Europe/Moscow",
    tier: 1,
    aliases: [
      "москва",
      "москвы",
      "москву",
      "москве",
      "мск",
      "msk",
      "mow",
      "svo",
      "dme",
      "vko",
      "шереметьево",
      "домодедово",
      "внуково",
      "столица",
    ],
  },
  {
    id: "LED",
    name: "Санкт-Петербург",
    iataCity: "LED",
    timezone: "Europe/Moscow",
    tier: 1,
    aliases: [
      "санкт-петербург",
      "санкт петербург",
      "петербург",
      "петербурга",
      "питер",
      "питера",
      "спб",
      "спб.",
      "led",
      "пулково",
      "ленинград",
    ],
  },
  {
    id: "OVB",
    name: "Новосибирск",
    iataCity: "OVB",
    timezone: "Asia/Novosibirsk",
    tier: 2,
    aliases: [
      "новосибирск",
      "новосибирска",
      "нск",
      "н-ск",
      "новосиб",
      "ovb",
      "толмачево",
      "толмачёво",
    ],
  },
  {
    id: "SVX",
    name: "Екатеринбург",
    iataCity: "SVX",
    timezone: "Asia/Yekaterinburg",
    tier: 2,
    aliases: [
      "екатеринбург",
      "екатеринбурга",
      "екб",
      "екат",
      "ебург",
      "свердловск",
      "svx",
      "кольцово",
    ],
  },
  {
    id: "KZN",
    name: "Казань",
    iataCity: "KZN",
    timezone: "Europe/Moscow",
    tier: 2,
    aliases: ["казань", "казани", "kzn"],
  },
  {
    id: "GOJ",
    name: "Нижний Новгород",
    iataCity: "GOJ",
    timezone: "Europe/Moscow",
    tier: 2,
    aliases: [
      "нижний новгород",
      "нижнего новгорода",
      "нижний",
      "нн",
      "н.новгород",
      "горький",
      "goj",
    ],
  },
  {
    id: "CEK",
    name: "Челябинск",
    iataCity: "CEK",
    timezone: "Asia/Yekaterinburg",
    tier: 3,
    aliases: ["челябинск", "челябинска", "челяба", "cek"],
  },
  {
    id: "KUF",
    name: "Самара",
    iataCity: "KUF",
    timezone: "Europe/Samara",
    tier: 2,
    aliases: ["самара", "самары", "курумоч", "kuf"],
  },
  {
    id: "OMS",
    name: "Омск",
    iataCity: "OMS",
    timezone: "Asia/Omsk",
    tier: 3,
    aliases: ["омск", "омска", "oms"],
  },
  {
    id: "ROV",
    name: "Ростов-на-Дону",
    iataCity: "ROV",
    timezone: "Europe/Moscow",
    tier: 2,
    aliases: [
      "ростов-на-дону",
      "ростов на дону",
      "ростов",
      "ростова",
      "рнд",
      "rov",
      "платов",
    ],
  },
  {
    id: "UFA",
    name: "Уфа",
    iataCity: "UFA",
    timezone: "Asia/Yekaterinburg",
    tier: 2,
    aliases: ["уфа", "уфы", "ufa"],
  },
  {
    id: "KJA",
    name: "Красноярск",
    iataCity: "KJA",
    timezone: "Asia/Krasnoyarsk",
    tier: 2,
    aliases: ["красноярск", "красноярска", "kja", "емельяново"],
  },
  {
    id: "VOZ",
    name: "Воронеж",
    iataCity: "VOZ",
    timezone: "Europe/Moscow",
    tier: 3,
    aliases: ["воронеж", "воронежа", "voz"],
  },
  {
    id: "PEE",
    name: "Пермь",
    iataCity: "PEE",
    timezone: "Asia/Yekaterinburg",
    tier: 3,
    aliases: ["пермь", "перми", "pee", "большое савино"],
  },
  {
    id: "VOG",
    name: "Волгоград",
    iataCity: "VOG",
    timezone: "Europe/Volgograd",
    tier: 3,
    aliases: ["волгоград", "волгограда", "сталинград", "vog"],
  },
  {
    id: "KRR",
    name: "Краснодар",
    iataCity: "KRR",
    timezone: "Europe/Moscow",
    tier: 2,
    aliases: ["краснодар", "краснодара", "krr", "пашковский"],
  },
  {
    id: "TJM",
    name: "Тюмень",
    iataCity: "TJM",
    timezone: "Asia/Yekaterinburg",
    tier: 3,
    aliases: ["тюмень", "тюмени", "tjm", "рощино"],
  },
  {
    id: "IKT",
    name: "Иркутск",
    iataCity: "IKT",
    timezone: "Asia/Irkutsk",
    tier: 2,
    aliases: ["иркутск", "иркутска", "ikt"],
  },
  {
    id: "KHV",
    name: "Хабаровск",
    iataCity: "KHV",
    timezone: "Asia/Vladivostok",
    tier: 2,
    aliases: ["хабаровск", "хабаровска", "khv"],
  },
  {
    id: "VVO",
    name: "Владивосток",
    iataCity: "VVO",
    timezone: "Asia/Vladivostok",
    tier: 2,
    aliases: ["владивосток", "владивостока", "владик", "vvo", "кневичи"],
  },
  {
    id: "KGD",
    name: "Калининград",
    iataCity: "KGD",
    timezone: "Europe/Kaliningrad",
    tier: 2,
    aliases: [
      "калининград",
      "калининграда",
      "кгд",
      "кёниг",
      "кениг",
      "кенигсберг",
      "kgd",
      "храброво",
    ],
  },
  {
    id: "AER",
    name: "Сочи",
    iataCity: "AER",
    timezone: "Europe/Moscow",
    tier: 1,
    aliases: ["сочи", "адлер", "aer", "сириус"],
  },
];

export const CITY_IDS = CITIES.map((city) => city.id);

export function getCity(id: string): CitySeed {
  const city = CITIES.find((item) => item.id === id);
  if (!city) {
    throw new Error(`Unknown city: ${id}`);
  }
  return city;
}
